PROMPT Upgrading SCHEMAS to r23...

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'

WHENEVER SQLERROR EXIT 1

SET FEEDBACK OFF
BEGIN
    IF NVL( LENGTH( '^PDB_ADMIN_PASSWORD' ), 0 ) = 0 THEN
        RAISE_APPLICATION_ERROR( -20000, 'PDB ADMIN password not provided' );
    END IF;
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
DECLARE
    L_RESULT NUMBER;
BEGIN
    SELECT
        1
    INTO
        L_RESULT
    FROM
        DUAL
    WHERE
        -- NOTE: Check if we're on the PDB
        SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME'
        AND EXISTS ( SELECT 1 FROM ALL_USERS WHERE USERNAME = 'ORDS_METADATA' )
        AND EXISTS ( SELECT 1 FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC' AND OBJECT_TYPE = 'SYNONYM' AND OBJECT_NAME = 'APEX_APPLICATION' );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR( -20000, 'This script must be executed in the "^PDB_NAME." PDB and ORDS and APEX must be installed' );
END;
/
SET FEEDBACK ON

-- SECTION: SYSDBA
SET FEEDBACK OFF
CONNECT SYS/"^PDB_ADMIN_PASSWORD" AS SYSDBA
SET FEEDBACK ON

-- SECTION: LIVESQL-848
Prompt Applying: GRANT EXECUTE ON DBMS_DATA_MINING TO ADMIN WITH GRANT OPTION....
-- DBMS_DATA_MINING is a package, not a role, so it requires an object privilege (EXECUTE)
-- Use WITH GRANT OPTION instead of WITH ADMIN OPTION to allow execution and delegation
GRANT EXECUTE ON DBMS_DATA_MINING TO "^PDB_ADMIN_USERNAME" WITH GRANT OPTION;

Prompt Applying: GRANT EXECUTE ON CTXSYS.CTX_DDL TO ADMIN WITH GRANT OPTION....
-- Using WITH GRANT OPTION instead of WITH ADMIN OPTION because
-- WITH ADMIN OPTION applies only to system privileges and roles,
-- while WITH GRANT OPTION is required for object privileges like EXECUTE
GRANT EXECUTE ON CTXSYS.CTX_DDL TO "^PDB_ADMIN_USERNAME" WITH GRANT OPTION;
-- !SECTION: LIVESQL-848
-- !SECTION: SYSDBA

-- SECTION: ADMIN
SET FEEDBACK OFF
CONNECT "^PDB_ADMIN_USERNAME"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: LIVESQL-848
Prompt Applying: GRANT EXECUTE ON DBMS_DATA_MINING TO LIVE_SQL_READ_WRITE_USER ....
GRANT EXECUTE ON DBMS_DATA_MINING TO LIVE_SQL_READ_WRITE_USER;

Prompt Applying: GRANT EXECUTE ON CTXSYS.CTX_DDL TO LIVE_SQL_READ_WRITE_USER ....
GRANT EXECUTE ON CTXSYS.CTX_DDL TO LIVE_SQL_READ_WRITE_USER;

Prompt Applying: GRANT CREATE MINING MODEL TO LIVE_SQL_READ_WRITE_USER ....
GRANT CREATE MINING MODEL TO LIVE_SQL_READ_WRITE_USER;
-- !SECTION: LIVESQL-848
-- !SECTION: ADMIN

-- SECTION: LIVE_SQL
SET FEEDBACK OFF
CONNECT "LIVE_SQL"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: Objects
-- !SECTION: Objects

-- SECTION: ORDS Endpoints
-- !SECTION: ORDS Endpoints

-- NOTE: Update the version after the upgrade
BEGIN
    SET_PARAMETER( 'VERSION', 'r23' );
END;
/
-- !SECTION: LIVE_SQL

PROMPT Upgrade on SCHEMAS to r23 complete

