PROMPT Applying LIVESQL-893 patch...

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'

WHENEVER SQLERROR EXIT 1

SET FEEDBACK OFF
BEGIN
    IF NVL( LENGTH( '^PDB_ADMIN_PASSWORD' ), 0 ) = 0 THEN
        RAISE_APPLICATION_ERROR( -20000, 'PDB ADMIN password not provided' );
    END IF;
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
DECLARE
    L_RESULT NUMBER;
BEGIN
    SELECT
        1
    INTO
        L_RESULT
    FROM
        DUAL
    WHERE
        -- NOTE: Check if we're on the PDB
        SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME'
        AND EXISTS ( SELECT 1 FROM ALL_USERS WHERE USERNAME = 'ORDS_METADATA' )
        AND EXISTS ( SELECT 1 FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC' AND OBJECT_TYPE = 'SYNONYM' AND OBJECT_NAME = 'APEX_APPLICATION' );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR( -20000, 'This script must be executed in the "^PDB_NAME." PDB and ORDS and APEX must be installed' );
END;
/
SET FEEDBACK ON

-- SECTION: SYSDBA
SET FEEDBACK OFF
CONNECT SYS/"^PDB_ADMIN_PASSWORD" AS SYSDBA
SET FEEDBACK ON
-- !SECTION: SYSDBA

-- SECTION: ADMIN
SET FEEDBACK OFF
CONNECT "^PDB_ADMIN_USERNAME"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: LIVESQL-893

-- NOTE: As part of enforcing read-only access for the LIVE_SQL_SAMPLE_SCHEMAS_USER role,
-- we are revoking existing SELECT privileges on each table individually,
-- and replacing them with explicit READ privileges.
-- This ensures users granted this role cannot perform SELECT FOR UPDATE or other unintended operations,
-- helping preserve data integrity and reduce the risk of accidental data manipulation.

-- Revoke the SELECT privilege from all the samples schemas
-- ACADEMIC
REVOKE SELECT ON AD.AD_ACADEMIC_SESSION FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_COURSE_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_DEPARTMENTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_EXAM_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_EXAM_RESULTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_EXAM_TYPE FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_FACULTY_COURSE_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_JOBS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_FACULTY_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_FACULTY_LOGIN_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_PARENT_INFORMATION FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_STUDENT_ATTENDANCE FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_STUDENT_COURSE_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_STUDENT_DETAILS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AD.AD_STUDENT_COURSE_INFO FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- ANALYTIC VIEWS
REVOKE SELECT ON AV.TIME_DIM FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AV.PRODUCT_DIM FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AV.GEOGRAPHY_DIM FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON AV.SALES_FACT FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- CUSTOMER ORDERS
REVOKE SELECT ON CO.ORDERS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.CUSTOMERS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.INVENTORY FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.ORDER_ITEMS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.PRODUCTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.SHIPMENTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON CO.STORES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- HUMAN RESOURCES
REVOKE SELECT ON HR.COUNTRIES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.DEPARTMENTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.EMPLOYEES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.JOBS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.JOB_HISTORY FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.LOCATIONS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON HR.REGIONS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- OLYMPIC DATA
REVOKE SELECT ON OLYM.OLYM_GAMES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_SPORTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_DISCIPLINES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_BASE_EVENTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_EVENTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_NATIONS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_ATHLETES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_ATHLETE_GAMES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_MEDALS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OLYM.OLYM_MEDALS_VIEW FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- ORDER ENTRY
REVOKE SELECT ON OE.CUSTOMERS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OE.ORDERS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OE.ORDER_ITEMS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OE.PRODUCT_INFORMATION FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON OE.CATEGORIES_TAB FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- PROJECTS
REVOKE SELECT ON PROJECTS.PROJECT_STATUS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECT_MILESTONES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECT_TASKS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECT_TASK_TODOS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECT_TASK_LINKS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON PROJECTS.PROJECTS_COMPLETED_V FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- SALES HISTORY
REVOKE SELECT ON SH.CHANNELS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.COSTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.COUNTRIES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.CUSTOMERS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.PRODUCTS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.PROMOTIONS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.SALES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.SUPPLEMENTARY_DEMOGRAPHICS FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SH.TIMES FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- SCOTT
REVOKE SELECT ON SCOTT.EMP FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;
REVOKE SELECT ON SCOTT.DEPT FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- WORLD
REVOKE SELECT ON WORLD.WORLD_POPULATION FROM LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- Grant the READ privilege for all the samples schemas
-- ACADEMIC
GRANT READ ON AD.AD_ACADEMIC_SESSION TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_COURSE_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_DEPARTMENTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_EXAM_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_EXAM_RESULTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_EXAM_TYPE TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_FACULTY_COURSE_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_JOBS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_FACULTY_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_FACULTY_LOGIN_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_PARENT_INFORMATION TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_STUDENT_ATTENDANCE TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_STUDENT_COURSE_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_STUDENT_DETAILS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AD.AD_STUDENT_COURSE_INFO TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- ANALYTIC VIEWS
GRANT READ ON AV.TIME_DIM TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AV.PRODUCT_DIM TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AV.GEOGRAPHY_DIM TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON AV.SALES_FACT TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- CUSTOMER ORDERS
GRANT READ ON CO.ORDERS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.CUSTOMERS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.INVENTORY TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.ORDER_ITEMS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.PRODUCTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.SHIPMENTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON CO.STORES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- HUMAN RESOURCES
GRANT READ ON HR.COUNTRIES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.DEPARTMENTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.EMPLOYEES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.JOBS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.JOB_HISTORY TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.LOCATIONS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON HR.REGIONS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- OLYMPIC DATA
GRANT READ ON OLYM.OLYM_GAMES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_SPORTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_DISCIPLINES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_BASE_EVENTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_EVENTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_NATIONS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_ATHLETES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_ATHLETE_GAMES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_MEDALS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OLYM.OLYM_MEDALS_VIEW TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- ORDER ENTRY
GRANT READ ON OE.CUSTOMERS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OE.ORDERS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OE.ORDER_ITEMS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OE.PRODUCT_INFORMATION TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON OE.CATEGORIES_TAB TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- PROJECTS
GRANT READ ON PROJECTS.PROJECT_STATUS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECT_MILESTONES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECT_TASKS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECT_TASK_TODOS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECT_TASK_LINKS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON PROJECTS.PROJECTS_COMPLETED_V TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- SALES HISTORY
GRANT READ ON SH.CHANNELS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.COSTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.COUNTRIES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.CUSTOMERS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.PRODUCTS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.PROMOTIONS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.SALES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.SUPPLEMENTARY_DEMOGRAPHICS TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SH.TIMES TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- SCOTT
GRANT READ ON SCOTT.EMP TO LIVE_SQL_SAMPLE_SCHEMAS_USER;
GRANT READ ON SCOTT.DEPT TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- WORLD
GRANT READ ON WORLD.WORLD_POPULATION TO LIVE_SQL_SAMPLE_SCHEMAS_USER;

-- !SECTION: LIVESQL-893
-- !SECTION: ADMIN

-- SECTION: LIVE_SQL
SET FEEDBACK OFF
CONNECT "LIVE_SQL"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: Objects
-- !SECTION: Objects

-- SECTION: ORDS Endpoints
-- !SECTION: ORDS Endpoints
-- !SECTION: LIVE_SQL

PROMPT LIVESQL-893 patch applied...
