services:
  db23:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
    volumes:
      - db_23:/opt/oracle/oradata/
    ports:
      - "1521:1521"
    networks:
      - appnet

  ords-node:
    image: container-registry.oracle.com/database/ords:latest
    platform: linux/amd64
    environment:
      - DBSERVICENAME=${ORACLE_PDB}
      - DBHOST=db23        # <-- direct reference to the service name
      - DBPORT=${DBPORT}
      - ORACLE_PWD=${ORACLE_PWD}
    volumes:
      - ords_config:/etc/ords/config
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --noproxy "localhost" -f -k http://localhost:8080/ords/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 150
    depends_on:
      db23:
        condition: service_healthy
    networks:
      - appnet

  wls:
    image: container-registry.oracle.com/middleware/weblogic:14.1.2.0-generic-jdk17-ol8-250424
    environment:
      - PRODUCTION_MODE=dev
      # These are the default configuration settings, no need to explicitly set:
      #   * `ADMIN_NAME`                  (default: `AdminServer`)
      #   * `ADMIN_LISTEN_PORT`           (default: `7001`)
      #   * `DOMAIN_NAME`                 (default: `base_domain`)
      #   * 'PRODUCTION_MODE              (default: `dev`)
      #   * `ADMINISTRATION_PORT_ENABLED` (default: `false`)
      #   * `ADMINISTRATION_PORT`         (default: `9002`)
    entrypoint: ["/bin/sh", "-c", "sleep 60 && /u01/oracle/createAndStartEmptyDomain.sh"]
    volumes:
      - ./:/u01/oracle/properties
    ports:
      - "7001:7001"
      - "9002:9002"
    depends_on:
      ords-node:
        condition: service_healthy
    networks:
      - appnet

volumes:
  ords_config:
  db_23:

networks:
  appnet:
    driver: bridge
