name: demo
services:
  db23:
    hostname: database
    image: container-registry.oracle.com/database/free:latest
    # environment:
    #   - ORACLE_PDB=FREEPDB1
    #   - ORACLE_PWD=oracle
    #   - DBHOST=database
    environment:
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - DBHOST=${DBHOST}
    volumes:
      - db_files:/opt/oracle/oradata/
    ports:
      - "1521:1521"
  ords-node1:
    # restart: on-failure
    hostname: ords-node
    image: container-registry.oracle.com/database/ords:latest
    platform: linux/amd64
    environment:
      - DBSERVICENAME=${ORACLE_PDB}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - ORACLE_PWD=${ORACLE_PWD}
    # mem_limit: 3g           
    # environment:
    #   - DBSERVICENAME=FREEPDB1
    #   - DBHOST=database
    #   - DBPORT=1521  
    #   - ORACLE_PWD=oracle
      #Modify JDK_JAVA_OPTIONS to adjust the JVM memory
        # Translation: 
        #   -Xms256m = Start the JVM with 256 MB heap
          # -Xmx1024m = Allow for aJVM  max heap size of 1 GB
        # This prevents Java from grabbing too much memory and hitting the container limit.
      # - JAVA_VM_OPTIONS=-Xms1024M -Xmx1024M
    volumes:
      - ords_config:/etc/ords/config
      - ./entrypoint.sh:/entrypoint.sh:ro  # Mount your script
    entrypoint: ["/bin/bash", "/entrypoint.sh"]  # Override entrypoint
      
      #- <apex_file_path>:/opt/oracle/apex
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --noproxy "localhost" -f -k http://localhost:8080/ords/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 150
    # depends_on:
    #   db23:
    #     condition: service_healthy
  # wls:
  #   hostname: wls
  #   image: container-registry.oracle.com/middleware/weblogic:14.1.2.0-generic-jdk17-ol8-250424
  #   depends_on:
  #     - db23
  #   entrypoint: ["/bin/sh", "-c", "sleep 60 && /u01/oracle/createAndStartEmptyDomain.sh"]
  #   volumes:
  #     - $PWD:/u01/oracle/properties
  #   ports:
  #     - "7001:7001"
  #     - "9002:9002"
    # depends_on:
    #   ords-node1:
    #     condition: service_healthy
volumes:
  ords_config:
  db_files:
  # wls_dom_props:


  # ords-node1:
  #   image: container-registry.oracle.com/database/ords:latest
  #   hostname: ords-node
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DBSERVICENAME=${ORACLE_PDB}
  #     - DBHOST=${DBHOST}
  #     - DBPORT=${DBPORT}
  #     - ORACLE_PWD=${ORACLE_PWD}
  #   volumes:
  #     - ./ords/entrypoint.sh:/entrypoint.sh:ro  # Mount your script
  #   entrypoint: ["/bin/bash", "/entrypoint.sh"]  # Override entrypoint
  #   depends_on:
  #     db23:
  #       condition: service_healthy
