CREATE TABLE OLYM_ATHLETES (
    ID NUMBER NOT NULL,
    ATHLETE_NAME VARCHAR2(255) NOT NULL,
    ATHLETE_GENDER VARCHAR2(10) NOT NULL
);

CREATE TABLE OLYM_ATHLETE_GAMES (
    ID NUMBER NOT NULL,
    ATHLETE_ID NUMBER NOT NULL,
    GAME_ID NUMBER NOT NULL,
    NATION_ID NUMBER NOT NULL
);

CREATE TABLE OLYM_BASE_EVENTS (
    ID NUMBER NOT NULL,
    DISCIPLINE_ID NUMBER NOT NULL,
    EVENT VARCHAR2(60) NOT NULL
);

CREATE TABLE OLYM_DISCIPLINES (
    ID NUMBER NOT NULL,
    SPORT_ID NUMBER NOT NULL,
    DISCIPLINE VARCHAR2(30) NOT NULL
);

CREATE TABLE OLYM_EVENTS (
    ID NUMBER NOT NULL,
    BASE_EVENT_ID NUMBER NOT NULL,
    EVENT_GENDER VARCHAR2(1) NOT NULL
);

CREATE TABLE OLYM_GAMES (
    ID NUMBER NOT NULL,
    YEAR NUMBER NOT NULL,
    SEASON VARCHAR2(10) NOT NULL,
    CITY VARCHAR2(30) NOT NULL
);

CREATE TABLE OLYM_MEDALS (
    ID NUMBER NOT NULL,
    EVENT_ID NUMBER NOT NULL,
    ATHLETE_GAME_ID NUMBER NOT NULL,
    MEDAL VARCHAR2(10) NOT NULL
);

CREATE TABLE OLYM_NATIONS (
    ID NUMBER NOT NULL,
    NATION VARCHAR2(3) NOT NULL
);

CREATE TABLE OLYM_SPORTS (
    ID NUMBER NOT NULL,
    SPORT VARCHAR2(30) NOT NULL
);