SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Dropping Live SQL METADATA schema...

WHENEVER SQLERROR CONTINUE

DROP USER LIVE_SQL CASCADE;

WHENEVER SQLERROR EXIT 1

PROMPT INFO: Live SQL METADATA schema dropped
PROMPT INFO: Live SQL METADATA uninstalled

EXIT