SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Dropping Live SQL METADATA objects...

WHENEVER SQLERROR CONTINUE
SET TERMOUT OFF

DROP PACKAGE USER_SCHEMAS;
DROP PACKAGE SCHEMA_MANAGEMENT;
DROP PACKAGE AUTHORIZATION;
DROP PROCEDURE REMOVE_PARAMETER;
DROP PROCEDURE SET_PARAMETER;
DROP FUNCTION GET_PARAMETER;
DROP FUNCTION DOES_PARAMETER_EXIST;
DROP FUNCTION IS_PARAMETER_NAME_VALID;
DROP TABLE ORACLE_SQL_ADMIN_USERS;
DROP TABLE ORACLE_SQL_SAVED_STATEMENTS;
DROP TABLE ORACLE_SQL_SAVED_SESSIONS;
DROP TABLE ORACLE_SQL_AREAS;
DROP TABLE ORACLE_SQL_PUBLISHED_CONTENT;
DROP TABLE ORACLE_SQL_TUT_MODULES;
DROP TABLE ORACLE_SQL_TUTORIALS;
DROP VIEW CONTENT_ITEMS_USER_METRICS;
DROP VIEW CONTENT_ITEMS;
DROP FUNCTION CONTENT_NORMALIZED_TABLE;
DROP MATERIALIZED VIEW CONTENT_DATABASE_VERSIONS_MV;
DROP TABLE WORKSHEETS;
DROP VIEW SCRIPTS_USER_METRICS;
DROP MATERIALIZED VIEW SCRIPTS_METRICS_MV;
DROP TABLE SCRIPTS_METRICS;
DROP TABLE SCRIPTS_STATEMENTS;
DROP TABLE SCRIPTS;
DROP VIEW TUTORIALS_USER_METRICS;
DROP MATERIALIZED VIEW TUTORIALS_METRICS_MV;
DROP TABLE TUTORIALS_METRICS;
DROP TABLE TUTORIALS_STEPS;
DROP TABLE TUTORIALS;
DROP TABLE CONTENT_CATEGORIES;
DROP TABLE STATEMENTS;
DROP TABLE SCHEMAS;
DROP TABLE DATABASES;
DROP TABLE USERS;
DROP TABLE ROLES;
DROP TABLE PARAMETERS;
DROP PACKAGE UTILITIES;
DROP TYPE USER_SCHEMA_T;
DROP TYPE VC2_TABLE_T;

SET TERMOUT ON
WHENEVER SQLERROR EXIT 1

PROMPT INFO: Live SQL METADATA objects dropped...