SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'

PROMPT INFO: Dropping Live SQL METADATA PDB...

WHENEVER SQLERROR CONTINUE

ALTER PLUGGABLE DATABASE "^PDB_NAME" CLOSE IMMEDIATE; 

WHENEVER SQLERROR EXIT 1

DROP PLUGGABLE DATABASE "^PDB_NAME" INCLUDING DATAFILES;

PROMPT INFO: Live SQL METADATA PDB dropped
PROMPT INFO: Live SQL METADATA uninstalled

EXIT
