-- Generated by ORDS REST Data Services 23.4.0.r3461619
-- Schema: LIVE_SQL  Date: Wed Apr 10 12:25:05 2024 
--

BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.livesql.app',
      p_base_path      => '/app/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'worksheet/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'worksheet/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    APP_PAGE CLOB;
BEGIN
    SELECT HTML_PAGE INTO APP_PAGE FROM APP_BUILD WHERE PAGE_ID = 1;
    HTP.P(APP_PAGE);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    APP_PAGE CLOB;
    header_clob_first_half CLOB;
    header_clob_second_half CLOB;
    footer_clob CLOB;
    scripts_clob CLOB;
    page_position number := NVL(to_number(:page_number), 1); -- If NULL, then page would be first (1 index)
    number_of_rows number default 24; -- This represents the offset for the content (tutorial & script combined)
    CURSOR tutorial_cursor IS (
        SELECT id AS id, NULL AS script_id, TITLE, DESCRIPTION ,PUBLISHED,FEATURED,SETUP_CODE,TAGS,SHARE_KEY,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,LIKES,EXECUTIONS,DB_VERSION,SETUP_DESCRIPTION
    FROM TUTORIALS

    UNION ALL

    SELECT NULL AS id, script_id, TITLE, DESCRIPTION ,PUBLISHED,FEATURED,SETUP_CODE,TAGS,SHARE_KEY,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,LIKES,EXECUTIONS,DB_VERSION,SETUP_DESCRIPTION
    FROM SCRIPTS
    ) offset (page_position - 1) * number_of_rows rows fetch next number_of_rows + 1 rows only;
    TYPE tutorial_type IS TABLE OF tutorial_cursor%ROWTYPE INDEX BY BINA' || 'RY_INTEGER;
    tutorial_table tutorial_type;
BEGIN
    -- Check if there''s a next tutorial or not.
    OPEN tutorial_cursor;
    FETCH tutorial_cursor BULK COLLECT INTO tutorial_table;
    CLOSE tutorial_cursor;
    SELECT HTML_PAGE INTO header_clob_first_half FROM APP_BUILD WHERE PAGE_ID = 2; -- The first half of the head in HTML (doctype and a section of <head>)
    SELECT HTML_PAGE INTO header_clob_second_half FROM APP_BUILD WHERE PAGE_ID = 6; -- The second half of the head in HTML (remaining section of <head>, then <body>)
    SELECT HTML_PAGE INTO scripts_clob FROM APP_BUILD WHERE PAGE_ID = 3; -- The scripts for main.js and require.js
    SELECT HTML_PAGE INTO footer_clob FROM APP_BUILD WHERE PAGE_ID = 5; -- The Live SQL app footer.
    HTP.P(header_clob_first_half);
    -- Insert the meta tags for description and links generated dynamically from ORDS in the <head> of HTML
    HTP.P(''<meta name="description" content="View tutorials and scripts. You can also create your own tutori' || 'als and share with others.">'');
    HTP.P(''<link rel="canonical" href="'' || owa_util.get_cgi_env(''REQUEST_SCHEME'') || '':'' || ''//'' || owa_util.get_cgi_env(''HTTP_HOST'') || owa_util.get_cgi_env(''SCRIPT_NAME'') || ''?page_number='' || to_char(page_position) || ''"/>'');
    IF page_position >= 2
    THEN
        HTP.P(''<link rel="prev" href="'' || owa_util.get_cgi_env(''SCRIPT_NAME'') || ''?page_number='' || to_char(page_position - 1) || ''"/>'');
    END IF;
    IF tutorial_table.count > number_of_rows
    THEN
        HTP.P(''<link rel="next" href="'' || owa_util.get_cgi_env(''SCRIPT_NAME'') || ''?page_number='' || to_char(page_position + 1) || ''"/>'');
    END IF;
    HTP.P(header_clob_second_half);
    -- Using the regexp_replace due to requirements from hydration, it expects the HTML to match the javascript generated page
    -- perfectly. Using the "render-to-string" library that is used by NextJS 12-, It seems that spaces and tabs should not be there
    -- so the regex should take care of that.
    H' || 'TP.P(regexp_replace(to_clob(
        ''<div class="app-Container">
            <div id="hydrate-header"></div>''), ''>[[:space:]]+<'', ''><''));
    HTP.P(regexp_replace(to_clob(
        ''<div id="hydrate-library">
            <div class="oj-web-applayout-content oj-sm-padding-0">
                <div class="livesql-main">
                    <div style="display: flex; flex-direction: column; height: 100%; overflow: auto;">
                        <div class="oj-bg-neutral-0">
                            <div class="oj-panel oj-panel-border-radius-0 oj-sm-padding-2x-vertical oj-sm-padding-4x-start">
                                <h4 class="oj-typography-subheading-xl">Library</h4>
                                <p>View tutorials and scripts. You can also create your own tutorials and share with others.</p>
                            </div>
                            <div class="oj-bg-primary border-style"></div>
                        </div>
                        <div style="height: ' || '75vh; overflow: scroll;">
                            <div>
                                <div class="aligned-items oj-sm-padding-4x-top">
                                    <oj-input-search class="oj-inputsearch oj-form-control oj-text-field oj-component oj-complete" style="width: 20%;" aria-label="Search"></oj-input-search>
                                    <oj-menu-button id="sort-menu" class="oj-button oj-component oj-enabled oj-default oj-button-outlined-chrome oj-button-text-icon-end oj-complete"></oj-menu-button>
                                    <oj-menu-button id="filter-menu" class="oj-button oj-component oj-enabled oj-default oj-button-outlined-chrome oj-button-text-icon-end oj-complete"></oj-menu-button>
                                </div>
                                <div class="oj-sm-padding-4x-top" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">''), ''>[[:space:]]+<'', ''><''));
                        -- Loop through the content table a' || 'nd create the content cards.
                        FOR tutorial_index IN 1 .. tutorial_table.count - 1
                        LOOP
                            HTP.P(regexp_replace(to_clob(''
                            <div>
                                <a style="text-decoration: none; color: inherit;" href="''|| owa_util.get_cgi_env(''SCRIPT_NAME'') || ''/'' || CASE WHEN tutorial_table(tutorial_index).id IS NULL THEN ''scripts/'' || REPLACE(TRIM(LOWER(regexp_replace(tutorial_table(tutorial_index).title,''[][!};:/\(+-@)=*.#$%^&{]'', '''' ))), '' '', ''-'') || ''-'' || tutorial_table(tutorial_index).script_id ELSE ''tutorials/'' || REPLACE(TRIM(LOWER(regexp_replace(tutorial_table(tutorial_index).title,''[][!};:/\(+-@)=*.#$%^&{]'', '''' ))), '' '', ''-'') || ''-'' || tutorial_table(tutorial_index).id END  || ''">
                                    <div>
                                        <oj-action-card class="oj-actioncard" style="width: 100%;" tabindex="0" role="button">
                                 ' || '           <div id="cardContainer" style="width: 100%;">
                                                <div class="action-card-header"><span class="oj-badge oj-badge-info oj-sm-margin-4x oj-typography-body-sm">'' || CASE WHEN tutorial_table(tutorial_index).id IS NULL THEN ''Script'' ELSE ''Tutorial'' END || ''</span></div>
                                                <div class="action-card-title"><h1 class="oj-sm-margin-4x oj-typography-heading-xs">''|| tutorial_table(tutorial_index).title ||''</h1></div>
                                                <div class="action-card-description"><p class="oj-sm-padding-4x-horizontal oj-typography-body-lg">''|| tutorial_table(tutorial_index).description ||''</p></div>
                                                <div class="action-card-created-by"><div class="oj-sm-padding-4x-horizontal oj-sm-margin-10x-top oj-sm-margin-4x-bottom oj-text-color-secondary">Created days ago by '' || tutorial_table(tutorial_index).created_by ||''</div><div class="oj-' || 'divider-top"><div class="oj-flex oj-sm-align-items-flex-start"><div class="oj-flex oj-sm-flex-items-initial oj-sm-padding-4x"><span class="oj-ux-ico-heart oj-typography-body-xl"></span><span class="oj-typography-body-lg oj-flex oj-sm-padding-2x-horizontal">861 likes</span><span class="oj-ux-ico-play oj-typography-body-xl oj-sm-padding-2x-horizontal"></span><span class="oj-typography-body-lg oj-flex">177 executions</span></div></div></div></div>
                                            </div>
                                        </oj-action-card>
                                    </div>
                                </a>    
                            </div>
                            ''),''>[[:space:]]+<'', ''><''));
                        END LOOP;
                        HTP.P(regexp_replace(''</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>'', ''>[[:space:]]+<'', ''><''));
 ' || '   HTP.P(footer_clob);
    HTP.P(to_clob(''<div id="hydrate-drawer"></div>
    </div>''));
    HTP.P(scripts_clob);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/tutorials/:tutorial_slug',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/tutorials/:tutorial_slug',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    tutorial_data tutorials%ROWTYPE;
    tutorial_steps_data tutorials_steps%ROWTYPE;
    head_clob CLOB;
    header_clob_first_half CLOB;
    header_clob_second_half CLOB;
    footer_clob CLOB;
    scripts_clob CLOB;
    tutorial_steps_clob CLOB;
    current_tutorial_id NUMBER;
    module_number number;
BEGIN
  current_tutorial_id := regexp_substr( ''-'' || :tutorial_slug ,''[^-]+$'');
  IF current_tutorial_id IS NULL
  THEN
      RAISE NO_DATA_FOUND;
  END IF;

  SELECT count(id) into module_number FROM TUTORIALS_STEPS WHERE TUTORIAL_ID = current_tutorial_id;
  SELECT * INTO tutorial_data FROM TUTORIALS WHERE ID = current_tutorial_id;
  SELECT HTML_PAGE into header_clob_first_half from APP_BUILD where page_id = 2;
  SELECT HTML_PAGE into header_clob_second_half from APP_BUILD where page_id = 6;
  SELECT HTML_PAGE into scripts_clob from APP_BUILD where page_id = 3;
  SELECT HTML_PAGE into head_clob from APP_BUILD where page_id = 4;
  SELECT HTML_PAGE into footer_clob from APP_BUIL' || 'D where page_id = 5;
  HTP.PRN(header_clob_first_half);
  HTP.PRN(''<meta name="description" content="''|| tutorial_data.description ||''">'');
  HTP.PRN(header_clob_second_half);
  HTP.PRN(regexp_replace(to_clob(
        ''<div id="hydrate-app" class="app-Container">
            <div id="hydrate-header"></div>''), ''>[[:space:]]+<'', ''><''));       
    HTP.PRN(regexp_replace(to_clob(''<div id="hydrate-content">
            <div class="oj-web-applayout-content oj-sm-padding-0">
                <div class="livesql-main">
                        <div class="oj-panel content-full-size-panel">
                            <div style="display: flex; flex-direction: column;">
                                <a href="'' || REPLACE(owa_util.get_cgi_env(''SCRIPT_NAME''), ''tutorials'', '''') || ''">
                                    <oj-button chroming="borderless"><span slot="startIcon" class="oj-ux-ico-chevron-left"></span>Back</oj-button>
                                </a>
                                ' || '<div class="content-data-full-size-panel">
                                    <div class="content-page__header oj-flex oj-sm-justify-content-space-between">
                                        <div>
                                            <h2 class="oj-flex oj-sm-wrap-wrap oj-typography-heading-sm content-name">
                                                <span class="oj-badge oj-badge-info">Tutorial</span>'' || tutorial_data.title || ''</h2>
'' || tutorial_data.description || ''</div>
                                    </div>'' ), ''>[[:space:]]+<'', ''><''));

    HTP.PRN(regexp_replace(''<div class="oj-flex oj-sm-justify-content-space-between">
                                    <div class="oj-flex oj-sm-flex-direction-column stat-column">
                                    <div><p class="stat-type oj-text-color-secondary">Contributer</p><b>'' || tutorial_data.created_by || ''</b></div><div><p class="stat-type oj-text-color-secondary">Likes</p><b>5</b></div></div>
              ' || '                      <div class="oj-flex oj-sm-flex-direction-column stat-column"><div><p class="stat-type oj-text-color-secondary">Database version</p><b>18c</b></div>
                                    <div><p class="stat-type oj-text-color-secondary">Execution times</p><b>'' || tutorial_data.executions || ''</b></div></div><div class="oj-flex oj-sm-flex-direction-column stat-column">
                                    <div><p class="stat-type oj-text-color-secondary">Modules</p><b>'' || module_number || ''</b></div><div><p class="stat-type oj-text-color-secondary">Tags</p><b>--</b></div></div><div class="oj-flex oj-sm-flex-direction-column stat-column"><div><p class="stat-type oj-text-color-secondary">Created</p><b>2 months ago</b></div></div></div>
                                    <div>'', ''>[[:space:]]+<'', ''><''));
                                        HTP.PRN(regexp_replace(''<p>
                                                <b>Modules</b>
                                     ' || '       </p>''
                                            , ''>[[:space:]]+<'', ''><''));
                                        HTP.PRN(''<ol>'');
                                        FOR tutorial_step_title IN (SELECT title, sorting FROM TUTORIALS_STEPS WHERE TUTORIAL_ID = current_tutorial_id ORDER BY sorting)
                                        LOOP
                                            HTP.PRN(''<li><a href="#module'' || tutorial_step_title.sorting || ''">'' || tutorial_step_title.title || ''</a></li>'');
                                        END LOOP;
                                        HTP.PRN(''</ol>'');
                                        FOR tutorial_step IN (SELECT * FROM TUTORIALS_STEPS WHERE TUTORIAL_ID = current_tutorial_id ORDER BY sorting)
                                        LOOP
                                            HTP.PRN(regexp_replace(''<div>
                                                <hr>
                                                <h5 id' || '="module'' || tutorial_step.sorting || ''"> '' || tutorial_step.sorting || ''. ''|| tutorial_step.title || ''</h5>
                                            </div>''
                                                , ''>[[:space:]]+<'', ''><''));
                                            HTP.PRN(''<div>'');
                                            HTP.PRN(regexp_replace(tutorial_step.content , ''>[[:space:]]+<'', ''><''));
                                            HTP.PRN(''</div>'');
                                        END LOOP; 
                    HTP.PRN(regexp_replace(to_clob(''</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            ''|| footer_clob ||''
            <div id="hydrate-drawer"></div>
            <div id="tutorial-'' || tutorial_data.title || '' '' || current_tutorial_id ||''"></div>
        </div>''), ''>[[:space:]]+<'', ''><''
    ));
  HTP.PRN(scrip' || 'ts_clob);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/scripts/:script_slug',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.livesql.app',
      p_pattern        => 'library/scripts/:script_slug',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'-- add the script version of the single page');

COMMIT;

END;
/