-- NOTE: This script is not intended to be used directly but through
--       install_pdb.sql

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Creating Live SQL METADATA Schema...

DEFINE SCHEMA_PASSWORD = '^1'
DEFINE DEFAULT_TABLESPACE = '^2'
DEFINE TEMPORARY_TABLESPACE = '^3'

CREATE USER LIVE_SQL
    IDENTIFIED BY "^SCHEMA_PASSWORD"
    DEFAULT TABLESPACE "^DEFAULT_TABLESPACE"
    TEMPORARY TABLESPACE "^TEMPORARY_TABLESPACE"
    QUOTA UNLIMITED ON "^DEFAULT_TABLESPACE";
GRANT CONNECT TO LIVE_SQL;
GRANT RESOURCE TO LIVE_SQL;
GRANT CREATE MATERIALIZED VIEW TO LIVE_SQL;
GRANT CREATE VIEW TO LIVE_SQL;
GRANT CREATE TABLE TO LIVE_SQL;
GRANT EXECUTE ON DBMS_CRYPTO TO LIVE_SQL;
GRANT EXECUTE ON DBMS_MVIEW TO LIVE_SQL;
GRANT ALTER ANY MATERIALIZED VIEW TO LIVE_SQL;
GRANT CTXAPP TO LIVE_SQL;

GRANT ORDS_ADMINISTRATOR_ROLE TO LIVE_SQL;

BEGIN
    ORDS.ENABLE_SCHEMA(
        P_ENABLED => TRUE,
        P_SCHEMA => 'LIVE_SQL',
        P_URL_MAPPING_TYPE => 'BASE_PATH',
        P_URL_MAPPING_PATTERN => 'live_sql',
        P_AUTO_REST_AUTH => TRUE
    );
    BEGIN
        DBMS_NETWORK_ACL_ADMIN.DROP_ACL (
            ACL => 'utl_http.xml'
        );
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    DBMS_NETWORK_ACL_ADMIN.CREATE_ACL (
        ACL          => 'utl_http.xml',
        DESCRIPTION  => 'HTTP ACL',
        PRINCIPAL    => 'LIVE_SQL',
        IS_GRANT     => TRUE,
        PRIVILEGE    => 'connect',
        START_DATE   => NULL,
        END_DATE     => NULL
    );
    DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE (
        ACL         => 'utl_http.xml',
        PRINCIPAL   => APEX_APPLICATION.G_FLOW_SCHEMA_OWNER,
        IS_GRANT    => TRUE,
        PRIVILEGE   => 'connect',
        POSITION    => NULL,
        START_DATE  => NULL,
        END_DATE    => NULL
    );

    COMMIT;
END;
/

PROMPT INFO: Live SQL METADATA Schema created
