-- NOTE: This script is not intended to be used directly but through install.sql

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'
DEFINE LEGACY_DATA_DIRECTORY = '^6'

WHENEVER SQLERROR EXIT 1

SET FEEDBACK OFF
BEGIN
    IF NVL( LENGTH( '^PDB_ADMIN_PASSWORD' ), 0 ) = 0 THEN
        RAISE_APPLICATION_ERROR( -20000, 'PDB ADMIN password not provided' );
    END IF;
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
DECLARE
    L_RESULT NUMBER;
BEGIN
    SELECT
        1
    INTO
        L_RESULT
    FROM
        DUAL
    WHERE
        -- NOTE: Check if we're on the PDB
        SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME'
        AND EXISTS ( SELECT 1 FROM ALL_USERS WHERE USERNAME = 'ORDS_METADATA' )
        AND EXISTS ( SELECT 1 FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC' AND OBJECT_TYPE = 'SYNONYM' AND OBJECT_NAME = 'APEX_APPLICATION' );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR( -20000, 'This script must be executed in the "^PDB_NAME." PDB and ORDS and APEX must be installed' );
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
CONNECT "^PDB_ADMIN_USERNAME"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- NOTE: We know ORDS is installed at this point so making the appropriate grants

GRANT INHERIT PRIVILEGES ON USER "^PDB_ADMIN_USERNAME" TO ORDS_METADATA;
GRANT ORDS_ADMINISTRATOR_ROLE TO "^PDB_ADMIN_USERNAME";

BEGIN
    ORDS.ENABLE_SCHEMA(
        P_ENABLED => TRUE,
        P_SCHEMA => NULL,
        P_URL_MAPPING_TYPE => 'BASE_PATH',
        P_URL_MAPPING_PATTERN => NULL,
        P_AUTO_REST_AUTH => TRUE
    );
    COMMIT;
END;
/

@@01_create_schema.sql '^PDB_ADMIN_PASSWORD' '^DEFAULT_TABLESPACE' '^TEMPORARY_TABLESPACE'
CREATE OR REPLACE DIRECTORY LEGACY_DATA_DIRECTORY AS '^LEGACY_DATA_DIRECTORY';
GRANT READ, WRITE ON DIRECTORY LEGACY_DATA_DIRECTORY TO LIVE_SQL;

CONNECT "LIVE_SQL"/"^PDB_ADMIN_PASSWORD"
@@02_create_objects.sql
@@03_seed_data.sql
-- NOTE: Commenting this out so that we can import the data from datapump into the
--       production environment
-- @@04_migrate_data.sql
@@05_import_ords_modules.sql

CONNECT "^PDB_ADMIN_USERNAME"/"^PDB_ADMIN_PASSWORD"
DROP DIRECTORY LEGACY_DATA_DIRECTORY;

PROMPT INFO: Live SQL METADATA installed

-- NOTE: Apply available upgrades
-- @@../upgrade/upgrade.sql ^PDB_NAME ^PDB_ADMIN_USERNAME ^PDB_ADMIN_PASSWORD ^DEFAULT_TABLESPACE ^TEMPORARY_TABLESPACE

EXIT
