SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Dropping Live SQL SCHEMAS schema...

WHENEVER SQLERROR CONTINUE

DROP USER LIVE_SQL CASCADE;

WHENEVER SQLERROR EXIT 1

PROMPT INFO: Live SQL SCHEMAS schema dropped
PROMPT INFO: Live SQL SCHEMAS uninstalled

EXIT