SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Dropping Live SQL SCHEMAS ORDS objects...

WHENEVER SQLERROR EXIT 1

BEGIN
    ORDS_ADMIN.DROP_REST_FOR_SCHEMA( P_SCHEMA => 'LIVE_SQL' );
    COMMIT;
END;
/

PROMPT INFO: Live SQL SCHEMAS ORDS objects dropped
