SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Dropping Live SQL SCHEMAS objects...

WHENEVER SQLERROR CONTINUE

SET TERMOUT OFF

BEGIN
    DBMS_SCHEDULER.DROP_JOB(
        JOB_NAME => 'PROCESS_SCHEMA_CREATION_JOB',
        FORCE => TRUE
    );
    -- NOTE: Program arguments are also dropped by this function
    DBMS_SCHEDULER.DROP_PROGRAM (
        PROGRAM_NAME => 'PROCES_SCH_CREATION_JOB_PROG',
        FORCE => TRUE
    );
END;
/

DROP PACKAGE SCHEMA_MANAGEMENT;
DROP TABLE SCHEMAS;
DROP TABLE SCHEMA_CREATION_JOBS;
DROP PACKAGE UTILITIES;
DROP PROCEDURE REMOVE_PARAMETER;
DROP PROCEDURE SET_PARAMETER;
DROP FUNCTION GET_PARAMETER;
DROP FUNCTION DOES_PARAMETER_EXIST;
DROP FUNCTION IS_PARAMETER_NAME_VALID;
DROP TABLE PARAMETERS;
DROP TYPE VC2_TABLE_T;

SET TERMOUT ON

WHENEVER SQLERROR EXIT 1

PROMPT INFO: Live SQL SCHEMAS objects dropped...