SET DEFINE '^'
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Uninstalling Live SQL SCHEMAS...

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'

COLUMN :UNINSTALL_CDB_SCRIPT NEW_VALUE UNINSTALL_CDB_SCRIPT NOPRINT
VARIABLE UNINSTALL_CDB_SCRIPT VARCHAR2(255)
COLUMN :UNINSTALL_PDB_SCRIPT NEW_VALUE UNINSTALL_PDB_SCRIPT NOPRINT
VARIABLE UNINSTALL_PDB_SCRIPT VARCHAR2(255)

WHENEVER SQLERROR EXIT 1

SET SERVEROUTPUT ON
SET FEEDBACK OFF
DECLARE
    L_ROW_COUNT NUMBER;

    L_IS_AT_CDB BOOLEAN := SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = 'CDB$ROOT';
    L_DOES_PDB_EXISTS BOOLEAN;

    L_IS_AT_PDB BOOLEAN := SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME';
    L_DOES_SCHEMA_EXISTS BOOLEAN;
BEGIN
    SELECT COUNT(1) INTO L_ROW_COUNT FROM V$PDBS WHERE NAME = '^PDB_NAME';
    L_DOES_PDB_EXISTS := L_ROW_COUNT = 1;
    SELECT COUNT(1) INTO L_ROW_COUNT FROM ALL_USERS WHERE USERNAME = 'LIVE_SQL';
    L_DOES_SCHEMA_EXISTS := L_ROW_COUNT >= 1;
    L_ROW_COUNT := NULL;

    :UNINSTALL_CDB_SCRIPT := '../../utilities/nothing.sql';
    :UNINSTALL_PDB_SCRIPT := '../../utilities/nothing.sql';

    IF L_IS_AT_CDB THEN
        IF L_DOES_PDB_EXISTS THEN
            :UNINSTALL_CDB_SCRIPT := 'uninstall_cdb.sql';
        ELSE
            DBMS_OUTPUT.PUT_LINE( 'WARNING: PDB "^PDB_NAME." does not exists. Did you mean to install instead?' );
        END IF;
    ELSIF L_IS_AT_PDB THEN
        IF L_DOES_SCHEMA_EXISTS THEN
            :UNINSTALL_PDB_SCRIPT := 'uninstall_pdb.sql';
        ELSE
            DBMS_OUTPUT.PUT_LINE( 'WARNING: Live SQL schemas do not exists. Did you mean to install instead?' );
        END IF;
    ELSE
        RAISE_APPLICATION_ERROR( -20000, 'This script is intended to be executed either on the "CDB$ROOT" or the "^PDB_NAME." PDB' );
    END IF;
END;
/
SET FEEDBACK ON
SET SERVEROUTPUT OFF
SET TERMOUT OFF
SELECT :UNINSTALL_CDB_SCRIPT FROM DUAL;
SELECT :UNINSTALL_PDB_SCRIPT FROM DUAL;
SET TERMOUT ON

@@^UNINSTALL_CDB_SCRIPT '^PDB_NAME'
@@^UNINSTALL_PDB_SCRIPT '^PDB_NAME' '^PDB_ADMIN_USERNAME' '^PDB_ADMIN_PASSWORD'

PROMPT INFO: Live SQL SCHEMAS uninstalled

EXIT
