SET DEFINE '^'
SET VERIFY OFF
SET ECHO OFF

DEFINE TABLE = '^1';

CREATE OR REPLACE TRIGGER "^TABLE._BU" BEFORE UPDATE ON "^TABLE" FOR EACH ROW
DECLARE
BEGIN
    :NEW.UPDATED_ON := CURRENT_TIMESTAMP;
END;
/
