-- NOTE: This script is not intended to be used directly but through
--       install_pdb.sql

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

PROMPT INFO: Creating Live SQL SCHEMAS Schema...

DEFINE SCHEMA_PASSWORD = '^1'
DEFINE DEFAULT_TABLESPACE = '^2'
DEFINE TEMPORARY_TABLESPACE = '^3'

CREATE USER LIVE_SQL
    IDENTIFIED BY "^SCHEMA_PASSWORD"
    DEFAULT TABLESPACE "^DEFAULT_TABLESPACE"
    TEMPORARY TABLESPACE "^TEMPORARY_TABLESPACE"
    QUOTA UNLIMITED ON "^DEFAULT_TABLESPACE";

GRANT CONNECT TO LIVE_SQL WITH ADMIN OPTION;
GRANT RESOURCE TO LIVE_SQL WITH ADMIN OPTION;
GRANT LIVE_SQL_SAMPLE_SCHEMAS_USER TO LIVE_SQL WITH ADMIN OPTION;
BEGIN
    IF DBMS_DB_VERSION.VER_LE_23 THEN
        EXECUTE IMMEDIATE 'GRANT CREATE DOMAIN TO LIVE_SQL WITH ADMIN OPTION';
    END IF;
END;
/

GRANT CREATE MATERIALIZED VIEW TO LIVE_SQL;
GRANT CREATE VIEW TO LIVE_SQL;
GRANT CREATE TABLE TO LIVE_SQL;
GRANT EXECUTE ON DBMS_CRYPTO TO LIVE_SQL;
GRANT EXECUTE ON DBMS_MVIEW TO LIVE_SQL;
GRANT ALTER ANY MATERIALIZED VIEW TO LIVE_SQL;
GRANT CTXAPP TO LIVE_SQL;
GRANT CREATE JOB TO LIVE_SQL;

GRANT ORDS_ADMINISTRATOR_ROLE TO LIVE_SQL;
GRANT EXECUTE ON ORDS_METADATA.OAUTH_ADMIN TO LIVE_SQL;
GRANT SELECT ON ORDS_METADATA.ORDS_SCHEMAS TO LIVE_SQL;
GRANT SELECT ON ORDS_METADATA.OAUTH_CLIENTS TO LIVE_SQL;
GRANT SELECT ON ORDS_METADATA.DBA_ORDS_URL_MAPPINGS TO LIVE_SQL;

GRANT CREATE USER TO LIVE_SQL;
GRANT ALTER USER TO LIVE_SQL;
GRANT DROP USER TO LIVE_SQL;

BEGIN
    BEGIN
        DBMS_NETWORK_ACL_ADMIN.DROP_ACL (
            ACL => 'utl_http.xml'
        );
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    DBMS_NETWORK_ACL_ADMIN.CREATE_ACL (
        ACL          => 'utl_http.xml',
        DESCRIPTION  => 'HTTP ACL',
        PRINCIPAL    => 'LIVE_SQL',
        IS_GRANT     => TRUE,
        PRIVILEGE    => 'connect',
        START_DATE   => NULL,
        END_DATE     => NULL
    );
    DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE (
        ACL         => 'utl_http.xml',
        PRINCIPAL   => APEX_APPLICATION.G_FLOW_SCHEMA_OWNER,
        IS_GRANT    => TRUE,
        PRIVILEGE   => 'connect',
        POSITION    => NULL,
        START_DATE  => NULL,
        END_DATE    => NULL
    );
    COMMIT;
END;
/


-- Create the roles to handle the necessary grants for each type of schema
CREATE ROLE LIVE_SQL_READ_ONLY_USER;
GRANT LIVE_SQL_READ_ONLY_USER TO LIVE_SQL WITH ADMIN OPTION;

CREATE ROLE LIVE_SQL_READ_WRITE_USER;
BEGIN
    IF DBMS_DB_VERSION.VER_LE_23 THEN
        EXECUTE IMMEDIATE 'GRANT CREATE DOMAIN TO LIVE_SQL_READ_WRITE_USER';
        EXECUTE IMMEDIATE 'GRANT CREATE PROPERTY GRAPH TO LIVE_SQL_READ_WRITE_USER';
        EXECUTE IMMEDIATE 'GRANT EXECUTE DYNAMIC MLE TO LIVE_SQL_READ_WRITE_USER';
        EXECUTE IMMEDIATE 'GRANT CREATE MLE TO LIVE_SQL_READ_WRITE_USER';
    END IF;
END;
/
GRANT LIVE_SQL_READ_WRITE_USER TO LIVE_SQL WITH ADMIN OPTION;

PROMPT INFO: Live SQL SCHEMAS Schema created

