
PROMPT applying r28-livesql-906 patch on metadata PDB...

-- SECTION: Checking database, PDB, and other details (This is needed in every patch file, so copy and paste it)
SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'

WHENEVER SQLERROR EXIT 1

SET FEEDBACK OFF
BEGIN
    IF NVL( LENGTH( '^PDB_ADMIN_PASSWORD' ), 0 ) = 0 THEN
        RAISE_APPLICATION_ERROR( -20000, 'PDB ADMIN password not provided' );
    END IF;
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
DECLARE
    L_RESULT NUMBER;
BEGIN
    SELECT
        1
    INTO
        L_RESULT
    FROM
        DUAL
    WHERE
        -- NOTE: Check if we're on the PDB
        SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME'
        AND EXISTS ( SELECT 1 FROM ALL_USERS WHERE USERNAME = 'ORDS_METADATA' )
        AND EXISTS ( SELECT 1 FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC' AND OBJECT_TYPE = 'SYNONYM' AND OBJECT_NAME = 'APEX_APPLICATION' );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR( -20000, 'This script must be executed in the "^PDB_NAME." PDB and ORDS and APEX must be installed' );
END;
/
SET FEEDBACK ON

-- SECTION: LIVE_SQL
SET FEEDBACK OFF
CONNECT "LIVE_SQL"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: Objects 

-- SECTION: LIVESQL-906
ALTER TABLE STATEMENTS DROP CONSTRAINT STATEMENTS_CHK1;
ALTER TABLE STATEMENTS ADD CONSTRAINT STATEMENTS_CHK1 CHECK (CODE_LANGUAGE IN ('PL_SQL', 'QUICK_SQL', 'JAVASCRIPT','SQL_PLUS'));

ALTER TABLE STATEMENTS DROP CONSTRAINT STATEMENTS_CHK3;
ALTER TABLE STATEMENTS ADD CONSTRAINT STATEMENTS_CHK3 CHECK (
    (
        CODE_LANGUAGE IN ( 'PL_SQL', 'JAVASCRIPT', 'SQL_PLUS' )
        AND JSON_EXISTS ( RESULT, '$.statementPos' )
        AND JSON_EXISTS ( RESULT, '$.response' )
        AND JSON_VALUE(RESULT, '$.statementId') IS NOT NULL
        AND JSON_VALUE(RESULT, '$.statementText') IS NOT NULL
        AND JSON_VALUE(RESULT, '$.statementType') IS NOT NULL
        AND JSON_VALUE(RESULT, '$.result') IS NOT NULL
        AND JSON_VALUE(RESULT, '$.statementTimestamp') IS NOT NULL
    )
    OR
    (
        CODE_LANGUAGE = 'QUICK_SQL'
        AND JSON_EXISTS ( RESULT, '$.env' )
        AND JSON_EXISTS ( RESULT, '$.items' )
    )
);
-- !SECTION: LIVESQL-906
-- !SECTION: Objects


-- IMPORTANT: Mention the end of the patch upgrade (something like 'r<number> patch applied...')
PROMPT r28-livesql-906 applied...
