PROMPT applying r32-livesql-1020 patch on metadata PDB...

-- SECTION: Checking database, PDB, and other details (This is needed in every patch file, so copy and paste it)
SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'

WHENEVER SQLERROR EXIT 1

SET FEEDBACK OFF
BEGIN
    IF NVL( LENGTH( '^PDB_ADMIN_PASSWORD' ), 0 ) = 0 THEN
        RAISE_APPLICATION_ERROR( -20000, 'PDB ADMIN password not provided' );
    END IF;
END;
/
SET FEEDBACK ON

SET FEEDBACK OFF
DECLARE
    L_RESULT NUMBER;
BEGIN
    SELECT
        1
    INTO
        L_RESULT
    FROM
        DUAL
    WHERE
        -- NOTE: Check if we're on the PDB
        SYS_CONTEXT( 'USERENV', 'CON_NAME' ) = '^PDB_NAME'
        AND EXISTS ( SELECT 1 FROM ALL_USERS WHERE USERNAME = 'ORDS_METADATA' )
        AND EXISTS ( SELECT 1 FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC' AND OBJECT_TYPE = 'SYNONYM' AND OBJECT_NAME = 'APEX_APPLICATION' );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR( -20000, 'This script must be executed in the "^PDB_NAME." PDB and ORDS and APEX must be installed' );
END;
/
SET FEEDBACK ON

-- !SECTION: DB Check

-- SECTION: ADMIN
-- NOTE: No upgrades needed
-- !SECTION: ADMIN


-- SECTION: LIVE_SQL
SET FEEDBACK OFF
CONNECT "LIVE_SQL"/"^PDB_ADMIN_PASSWORD"
SET FEEDBACK ON

-- SECTION: Objects 
-- !SECTION: Objects

-- SECTION: ORDS Endpoints
-- SECTION: LIVESQL-1020
DECLARE
    SAMPLE_SCHEMAS_TEMPLATE_ID NUMBER;
    SAMPLE_SCHEMAS_URI VARCHAR2(600) := 'sample_schemas/';
BEGIN
    SELECT
        ID
    INTO
        SAMPLE_SCHEMAS_TEMPLATE_ID
    FROM
        USER_ORDS_TEMPLATES
    WHERE
        URI_TEMPLATE = SAMPLE_SCHEMAS_URI;
    
    ORDS_SERVICES.DELETE_TEMPLATE(p_id => SAMPLE_SCHEMAS_TEMPLATE_ID);
    
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE( 'The template uri ''' || SAMPLE_SCHEMAS_URI || ''' does not exists');
END;
-- !SECTION: LIVESQL-1020
/
-- !SECTION: ORDS Endpoints

-- !SECTION: LIVE_SQL

PROMPT r32-livesql-1020 applied...
