-- NOTE: This script is not intended to be used directly but through install_pdb.sql

PROMPT INFO: Applying Live SQL METADATA upgrades...

SET DEFINE '^'
SET ESCAPE OFF
SET ESCAPE '\'
SET VERIFY OFF
SET ECHO OFF

DEFINE PDB_NAME = '^1'
DEFINE PDB_ADMIN_USERNAME = '^2'
DEFINE PDB_ADMIN_PASSWORD = '^3'
DEFINE DEFAULT_TABLESPACE = '^4'
DEFINE TEMPORARY_TABLESPACE = '^5'

@@beta2.sql ^PDB_NAME ^PDB_ADMIN_USERNAME ^PDB_ADMIN_PASSWORD ^DEFAULT_TABLESPACE ^TEMPORARY_TABLESPACE
@@r23.sql ^PDB_NAME ^PDB_ADMIN_USERNAME ^PDB_ADMIN_PASSWORD ^DEFAULT_TABLESPACE ^TEMPORARY_TABLESPACE
@@r28.sql ^PDB_NAME ^PDB_ADMIN_USERNAME ^PDB_ADMIN_PASSWORD ^DEFAULT_TABLESPACE ^TEMPORARY_TABLESPACE

-- TODO: replace r30 patches with the corresponding r30.sql upgrade script 
@@r31.sql ^PDB_NAME ^PDB_ADMIN_USERNAME ^PDB_ADMIN_PASSWORD ^DEFAULT_TABLESPACE ^TEMPORARY_TABLESPACE

PROMPT INFO: Live SQL METADATA upgrades applied
